export const COMMENT_CHANGED = 'COMMENT_CHANGED';
export const SEND_COMMENT = 'SEND_COMMENT';
export const SET_LIKED = 'SET_LIKED';
export const SET_SUBCOMMENT_LIKED = 'SET_SUBCOMMENT_LIKED';
export const SET_PARENT_ID = 'SET_PARENT_ID';
export const SET_SUBCOMMENT_ID = 'SET_SUBCOMMENT_ID';
